In [26]:
import pandas as pd
import matplotlib.pyplot as plt
import os

In [27]:
print(os.getcwd()) # Get Current Working Directory ดูว่าเราอยู่ที่ไหนในระบบไฟล์

d:\Phee\Python project\streamlit-Dashboard\eda

In [28]:
df = pd.read_csv('../assets/AI_Job_Market_Trends_2026.csv')
df

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency,job_openings
0,1,AI Engineer,Startup,Retail,Canada,Remote,Senior,2,Master,0,0,0,1,0,158322,6,2024,Low,4
1,2,Machine Learning Engineer,MNC,Technology,Australia,Hybrid,Mid,0,Bachelor,1,1,1,0,1,163666,11,2026,High,9
2,3,Machine Learning Engineer,MNC,Technology,Germany,Onsite,Mid,14,Master,1,0,1,0,1,158556,3,2026,High,9
3,4,Business Analyst,Startup,Healthcare,Germany,Remote,Mid,9,Master,0,1,0,1,1,95775,3,2025,High,7
4,5,Data Scientist,MNC,Healthcare,Germany,Hybrid,Mid,5,Master,1,1,1,0,0,111873,12,2021,Low,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10340,10341,Data Engineer,Startup,Technology,USA,Onsite,Entry,2,PhD,1,0,1,0,1,76426,4,2023,Low,4
10341,10342,Data Analyst,Medium,Healthcare,Australia,Hybrid,Entry,10,Master,1,1,0,0,1,61233,9,2024,Medium,6
10342,10343,Machine Learning Engineer,Startup,Education,Germany,Hybrid,Entry,4,PhD,0,0,0,1,0,103681,3,2026,Low,4
10343,10344,Data Engineer,MNC,E-commerce,Canada,Hybrid,Mid,5,PhD,1,1,1,0,0,112895,12,2024,High,9
10344,10345,AI Engineer,Startup,Education,Australia,Onsite,Mid,12,PhD,0,1,1,1,1,159570,11,2022,High,3

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10345 entries, 0 to 10344
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   job_id                10345 non-null  int64
 1   job_title             10345 non-null  object
 2   company_size          10345 non-null  object
 3   company_industry      10345 non-null  object
 4   country               10345 non-null  object
 5   remote_type           10345 non-null  object
 6   experience_level      10345 non-null  object
 7   years_experience      10345 non-null  int64
 8   education_level       10345 non-null  object
 9   skills_python         10345 non-null  int64
 10  skills_sql            10345 non-null  int64
 11  skills_ml             10345 non-null  int64
 12  skills_deep_learning  10345 non-null  int64
 13  skills_cloud          10345 non-null  int64
 14  salary                10345 non-null  int64
 15  job_posting_month     10345 non-null  int64
 16  job_posting_year      10345 non-null  int64
 17  hiring_urgency        10345 non-null  object
 18  job_openings          10345 non-null  int64
dtypes: int64(11), object(8)
memory usage: 1.5+ MB

In [30]:
df.describe() # อย่าอ่านข้อมูลที่เป็น 0,1 เพราะเป็นข้อมูลเชิงหมวดหมู่ ไม่ใช่ตัวเลข

,job_id,years_experience,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,job_openings
count,10345.000000,10345.000000,10345.000000,10345.000000,10345.000000,10345.000000,10345.000000,10345.00000,10345.000000,10345.000000,10345.00000
mean,5173.000000,6.950507,0.493088,0.503045,0.507878,0.498018,0.511455,113438.22726,6.502465,2023.000387,5.00406
std,2986.488601,4.320054,0.499976,0.500015,0.499962,0.500020,0.499893,31389.20106,3.473441,1.996856,2.58382
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,45083.00000,1.000000,2020.000000,1.00000
25%,2587.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,89715.00000,4.000000,2021.000000,3.00000
50%,5173.000000,7.000000,0.000000,1.000000,1.000000,0.000000,1.000000,113082.00000,6.000000,2023.000000,5.00000
75%,7759.000000,11.000000,1.000000,1.000000,1.000000,1.000000,1.000000,134894.00000,10.000000,2025.000000,7.00000
max,10345.000000,14.000000,1.000000,1.000000,1.000000,1.000000,1.000000,204143.00000,12.000000,2026.000000,9.00000

Cleaning Data

In [31]:
df_clean_dashboard = df.drop(columns = ['job_id', 'job_posting_month'])
df_clean_dashboard

,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_year,hiring_urgency,job_openings
0,AI Engineer,Startup,Retail,Canada,Remote,Senior,2,Master,0,0,0,1,0,158322,2024,Low,4
1,Machine Learning Engineer,MNC,Technology,Australia,Hybrid,Mid,0,Bachelor,1,1,1,0,1,163666,2026,High,9
2,Machine Learning Engineer,MNC,Technology,Germany,Onsite,Mid,14,Master,1,0,1,0,1,158556,2026,High,9
3,Business Analyst,Startup,Healthcare,Germany,Remote,Mid,9,Master,0,1,0,1,1,95775,2025,High,7
4,Data Scientist,MNC,Healthcare,Germany,Hybrid,Mid,5,Master,1,1,1,0,0,111873,2021,Low,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10340,Data Engineer,Startup,Technology,USA,Onsite,Entry,2,PhD,1,0,1,0,1,76426,2023,Low,4
10341,Data Analyst,Medium,Healthcare,Australia,Hybrid,Entry,10,Master,1,1,0,0,1,61233,2024,Medium,6
10342,Machine Learning Engineer,Startup,Education,Germany,Hybrid,Entry,4,PhD,0,0,0,1,0,103681,2026,Low,4
10343,Data Engineer,MNC,E-commerce,Canada,Hybrid,Mid,5,PhD,1,1,1,0,0,112895,2024,High,9
10344,AI Engineer,Startup,Education,Australia,Onsite,Mid,12,PhD,0,1,1,1,1,159570,2022,High,3

In [32]:
df_clean_dashboard.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10345 entries, 0 to 10344
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   job_title             10345 non-null  object
 1   company_size          10345 non-null  object
 2   company_industry      10345 non-null  object
 3   country               10345 non-null  object
 4   remote_type           10345 non-null  object
 5   experience_level      10345 non-null  object
 6   years_experience      10345 non-null  int64
 7   education_level       10345 non-null  object
 8   skills_python         10345 non-null  int64
 9   skills_sql            10345 non-null  int64
 10  skills_ml             10345 non-null  int64
 11  skills_deep_learning  10345 non-null  int64
 12  skills_cloud          10345 non-null  int64
 13  salary                10345 non-null  int64
 14  job_posting_year      10345 non-null  int64
 15  hiring_urgency        10345 non-null  object
 16  job_openings          10345 non-null  int64
dtypes: int64(9), object(8)
memory usage: 1.3+ MB

In [ ]:
#df_clean_dashboard = df_clean_dashboard.groupby(by=["job_title"]).mean()[["salary"]] #บวกไม่ได้เพราะมี object อยู่ใน column อื่น
df_average_salary = df_clean_dashboard.groupby(by=["job_title"])[["salary"]].mean()#[] จะไม่มีตาราง [[]] จะมีตาราง

                                  salary
job_title
AI Engineer                139934.655370
Business Analyst           101642.028765
Data Analyst                99136.475745
Data Engineer               99711.085322
Data Scientist              99645.837933
Machine Learning Engineer  139705.422989

In [48]:
df_average_salary.reset_index()

                   job_title         salary
0                AI Engineer  139934.655370
1           Business Analyst  101642.028765
2               Data Analyst   99136.475745
3              Data Engineer   99711.085322
4             Data Scientist   99645.837933
5  Machine Learning Engineer  139705.422989