In [32]:
import pandas as pd
import matplotlib.pyplot as plt
import os

In [33]:
print(os.getcwd()) #Get Current Working Directory ดูว่าเราอยู่ที่ไหนในระบบไฟล์

d:\Phee\Python project\streamlit-Dashboard\eda

In [34]:
df = pd.read_csv('../assets/tech_layoffs_2026_tracker.csv') #ถอย 1 ก้าวแล้วหา assets
df.head()

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,...,layoffs_2024,layoffs_2025,verified_source,month,quarter,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct,data_as_of
0,Amazon,2026-01-15,16000,2.7,E-Commerce/Cloud,USA,Seattle,False,Reduce bureaucracy and management layers,716.9,...,4000,14000,CNBC / NetworkWorld,January 2026,Q1 2026,North America,Mega (5K+),Positive,1.03,"March 18, 2026"
1,Block,2026-02-28,4000,40.0,Fintech,USA,San Francisco,True,AI tools replace roles enabling smaller teams,22.4,...,0,1000,CNBC / Crunchbase,February 2026,Q1 2026,North America,Large (2K-5K),Positive,40.00,"March 18, 2026"
2,Meta Reality Labs,2026-01-20,1500,10.0,Social Media/VR,USA,Menlo Park,True,Pivot from metaverse to AI research,164.5,...,0,500,InformationWeek / NYT,January 2026,Q1 2026,North America,Medium (500-2K),Positive,1.90,"March 18, 2026"
3,Atlassian,2026-03-14,1600,10.0,Enterprise Software,Australia,Sydney,True,Pivot to AI-first company strategy,5.1,...,0,500,TechRepublic / Metaintro,March 2026,Q1 2026,Asia-Pacific,Medium (500-2K),Positive,10.00,"March 18, 2026"
4,Oracle,2026-02-01,30000,15.0,Enterprise Software,USA,Austin,True,AI data centres replace human ops,52.9,...,6000,10000,IBTimes,February 2026,Q1 2026,North America,Mega (5K+),Positive,15.00,"March 18, 2026"

In [35]:
df.info()
print("-"*100)
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   company                        28 non-null     object
 1   layoff_date                    28 non-null     object
 2   jobs_cut                       28 non-null     int64
 3   pct_workforce_cut              28 non-null     float64
 4   sector                         28 non-null     object
 5   country                        28 non-null     object
 6   hq_city                        28 non-null     object
 7   ai_cited                       28 non-null     bool
 8   reason_stated                  28 non-null     object
 9   company_revenue_2025_bn        28 non-null     float64
 10  pre_layoff_headcount           28 non-null     int64
 11  stock_change_day_pct           28 non-null     float64
 12  simultaneous_ai_investment_bn  28 non-null     float64
 13  roles_most_affected            28 non-null     object
 14  replacement_roles              28 non-null     object
 15  ceo_quote                      28 non-null     object
 16  layoffs_2024                   28 non-null     int64
 17  layoffs_2025                   28 non-null     int64
 18  verified_source                28 non-null     object
 19  month                          28 non-null     object
 20  quarter                        28 non-null     object
 21  region                         28 non-null     object
 22  layoff_size_category           28 non-null     object
 23  stock_reaction                 28 non-null     object
 24  laid_off_vs_headcount_pct      28 non-null     float64
 25  data_as_of                     28 non-null     object
dtypes: bool(1), float64(5), int64(4), object(16)
memory usage: 5.6+ KB
----------------------------------------------------------------------------------------------------

,jobs_cut,pct_workforce_cut,company_revenue_2025_bn,pre_layoff_headcount,stock_change_day_pct,simultaneous_ai_investment_bn,layoffs_2024,layoffs_2025,laid_off_vs_headcount_pct
count,28.000000,28.000000,28.00000,2.800000e+01,28.000000,28.000000,28.000000,28.000000,28.000000
mean,3612.357143,10.639286,63.62500,1.076631e+05,0.832143,14.046429,944.642857,1951.785714,10.452143
std,6546.591373,10.433505,139.44986,2.915339e+05,1.742721,34.751824,1615.511574,3328.482085,10.719330
min,50.000000,0.100000,0.00000,2.500000e+03,-2.100000,0.000000,0.000000,0.000000,0.320000
25%,989.500000,2.525000,3.50000,8.750000e+03,-0.325000,0.000000,0.000000,0.000000,1.975000
50%,1000.000000,7.750000,9.40000,1.850000e+04,0.650000,0.450000,0.000000,500.000000,7.205000
75%,2050.000000,15.000000,53.90000,8.050000e+04,1.850000,2.250000,1125.000000,1812.500000,15.810000
max,30000.000000,40.000000,716.90000,1.550000e+06,5.800000,115.000000,6000.000000,14000.000000,40.000000

In [ ]:
df[['jobs_cut','month']] #There are so many columns im getting lazy now
#why was i choose this dataset god damn it

#jobs_cut คือการลดตำแหน่งงาน ไม่รับเพิ่ม ในช่วงเวลานั้นๆ

    jobs_cut          month
0      16000   January 2026
1       4000  February 2026
2       1500   January 2026
3       1600     March 2026
4      30000  February 2026
5       1000   January 2026
6       1000   January 2026
7        800   January 2026
8        675  February 2026
9       1600   January 2026
10      1700   January 2026
11      2000  February 2026
12      1000   January 2026
13      2000  February 2026
14      6000  February 2026
15       363  February 2026
16       958     March 2026
17      1000     March 2026
18      5000   January 2026
19        50  February 2026
20       500  February 2026
21      1000  February 2026
22      1000   January 2026
23      2200   January 2026
24       200     March 2026
25      1000     March 2026
26     16000     March 2026
27      1000     March 2026